### ISSUE TITLE
우분투 ethos 관련 번역 및 업데이트

### ISSUE THREAD

**Issue by NayeonKeum** [ubuntu-kr/disclosures.ubuntu-kr.org#5]
현재 [`docs/legal/ethos`](https://github.com/ubuntu-kr/disclosures.ubuntu-kr.org/tree/main/docs/legal/ethos) 아래의 행동강령 문서 중 `divesity.md(다양성 정책)`을 제외한 `index.md`, `code-of-conduct.md(우분투 행동강령)`, `mission.md(우리의 사명)`가 미번역 상태입니다.

CoC의 경우 기존에 @onting 님과 @hotheadfactory 님께서 작성하신 PR #1 을 현재 main branch에 맞게 업데이트한 뒤 머지하고, 

새로운 브랜치를 통해 전체 번역 추가하는 방식으로 수정하겠습니다.

 @sukso96100 @Junsang-Mun

**Comment by sukso96100** [comment]
@minwook-shin 님도 시간 나실 때 번역 검토 등 부탁드려요
